//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitySpaceShipData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommunityGardenEntities : DbContext
    {
        public CommunityGardenEntities()
            : base("name=CommunityGardenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Neighbor> Neighbors { get; set; }
        public virtual DbSet<Park> Parks { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Shareable> Shareables { get; set; }
        public virtual DbSet<ShareEvent> ShareEvents { get; set; }
        public virtual DbSet<SharePackage> SharePackages { get; set; }
    }
}
