//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitySpaceShipData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Neighbor
    {
        public int NeighborID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int SpaceShipID { get; set; }
        public int TeamID { get; set; }
        public int StatusID { get; set; }
        public bool IsMobile { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
    }
}
