//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitySpaceShipData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShareEvent()
        {
            this.SharePackages = new HashSet<SharePackage>();
        }
    
        public int ShareEventID { get; set; }
        public int ParkID { get; set; }
        public int Coordinator { get; set; }
        public System.DateTime Date { get; set; }
        public byte StartTime { get; set; }
        public byte EndTime { get; set; }
    
        public virtual Neighbor Neighbor { get; set; }
        public virtual Park Park { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharePackage> SharePackages { get; set; }
    }
}
