//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitySpaceShipData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharePackage
    {
        public int SharePackageID { get; set; }
        public int ShareableID { get; set; }
        public int Quantity { get; set; }
        public int ShareEventID { get; set; }
        public int NeighborID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Neighbor Neighbor { get; set; }
        public virtual Shareable Shareable { get; set; }
        public virtual ShareEvent ShareEvent { get; set; }
    }
}
