//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunitySpaceShipData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceShip
    {
        public int SpaceShipID { get; set; }
        public string CommunityName { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int ServiceStatus { get; set; }
        public int ProductionStatus { get; set; }
        public int EducationStatus { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual SpaceShipStatus SpaceShipStatus { get; set; }
        public virtual SpaceShipStatus SpaceShipStatus1 { get; set; }
        public virtual SpaceShipStatus SpaceShipStatus2 { get; set; }
    }
}
